### ISSUE TITLE
Thread is in running forever

### ISSUE THREAD

**Issue by slice-sunil** [rudderlabs/rudder-sdk-android#113]
Hi Team,
We are using another library in our application, which internally uses com.rudderstack.android.
After User press back button from the app, the thread created by the sdk doesn't die. It keeps on running, which causes battery drain issue for our customers

Following is the stacktrace of the thread details

`java.util.concurrent.LinkedBlockingQueue.size(LinkedBlockingQueue.java:304)
java.util.AbstractCollection.isEmpty(AbstractCollection.java:86)
com.rudderstack.android.sdk.core.DBInsertion.run(DBPersistentManager.java:238)`

**Comment by desusai7** [comment]
Hey @slice-sunil , 
Can you please share the version of the Rudder Android SDK you are running on ?

**Comment by slice-sunil** [comment]
@desusai7 com.rudderstack.android.sdk:core:1.0.21

**Comment by desusai7** [comment]
@slice-sunil, Can you please upgrade to the latest version of the SDK `1.4.0`, we had resolved this already. 

Closing the issue for now, feel free to re-open if you had any issues even after upgrading
