### ISSUE TITLE
Exposing RudderProperty's getMap() function

### ISSUE THREAD

**Issue by JamesNitsch** [rudderlabs/rudder-sdk-android#121]
RudderProperty's underlying map variable is currently inaccessible to outside callers via direct access or the protected 'getMap()' function. This makes it troublesome to enumerate over the properties in the map, as one may want to do while ensuring that the correct properties were passed in a unit test.

Can we expose RudderProperty's map member, or have a toString function that lists all properties for the purpose of unit testing the properties contained within. Without this, is it difficult to construct a proper failure message when the properties don't match.

**Comment by itsdebs** [comment]
Exposing the internal map will make it susceptible to unwanted modifications and side effects. Hence we cannot take this feature into consideration at present.
