### ISSUE TITLE
Request: remove BLUETOOTH permission

### ISSUE THREAD

**Issue by cmathew** [rudderlabs/rudder-sdk-android#127]
I see that this permission is used to populate the isBluetoothEnabled boolean inside RudderNetwork. Can this be removed, or can this be made optional to consumers of the library somehow? 

The problem is, we are seeing the BLUETOOTH permission in our app's merged manifest, which might confuse/alarm our users.

**Comment by desusai7** [comment]
Hey @cmathew , We had just released version 1.6.0 of the Android SDK which doesn't mandates the Bluetooth permission and includes Bluetooth status in context.network only if the app already has Bluetooth permission in it
