### ISSUE TITLE
Implimenting CI pipeline via github action to rudder-sdk-android repository

### ISSUE THREAD

**Issue by gaurangkudale** [rudderlabs/rudder-sdk-android#142]
Hey there, 

I just have one idea about implementing the CI pipeline to this repo. I can help here to implement CI pipeline
What do you guys think about this?

**Comment by desusai7** [comment]
Hey @gaurangkudale , 

Thanks for reaching out, and I definitely appreciate your willingness to help here. We are currently working on implementing the CI pipeline through GH Actions internally and it's almost done and will be live sometime, and closing this for now.
