### ISSUE TITLE
rudder sdk flutter error

### ISSUE THREAD

**Issue by Kev1ntan** [rudderlabs/rudder-sdk-android#151]
Hi, i got error when using flutter 2.2.0, 2.1.1, 2.1.0, 2.0.1

![image (4)](https://user-images.githubusercontent.com/55968084/198937871-b39d8f2d-c4d6-47ac-bd21-6dafdf37b853.png)

can help to solve this issue?

**Comment by desusai7** [comment]
Hey @Kev1ntan , 
Can you please try adding `mavenCentral()` to your `build.gradle` file as shown [here](https://github.com/rudderlabs/rudder-sdk-flutter/blob/33a718092fdfcc5549d11f573bf60ba82588ccef/rudder_plugin/example/android/build.gradle#L4) and [here](https://github.com/rudderlabs/rudder-sdk-flutter/blob/33a718092fdfcc5549d11f573bf60ba82588ccef/rudder_plugin/example/android/build.gradle#L17)

**Comment by jaumard** [comment]
Maybe because you still have jcenter (https://github.com/rudderlabs/rudder-sdk-android/blob/master/build.gradle#L23) ?

**Comment by desusai7** [comment]
I see, can you please try once removing jcenter() once from your codebase and let me know if this fixes the issue, meanwhile we will work from our side to remove them from the SDK !

**Comment by jaumard** [comment]
I've dig more on this on my side, and in fact it is not the flutter rudder stack package that cause this issue but another one that still have jcenter, once I remove jcenter from that other package ([contacts_service](https://github.com/lukasgit/flutter_contacts) on my side) , no more issue. Bad luck that the failing package was yours ^^

**Comment by desusai7** [comment]
I see that this issue has been resolved for @jaumard, and also we've completely removed the references to `jcenter()` in our latest version of Android SDK which is `1.7.1`, so this issue should be completely solved now. 

@Kev1ntan, please try re-installing the Flutter SDK and ensure that version `1.7.1` of Android SDK is downloaded, and this should fix the issue. 

Closing this issue, for now, please feel free to re-open it, if you are still facing this issue.
