### ISSUE TITLE
Crash due to database version downgrade with latest sdk

### ISSUE THREAD

**Issue by hbb20** [rudderlabs/rudder-sdk-android#155]
[Rudderstack Android Documnetation](https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-android-sdk/) mentions to use version `1+` (which is not a good practice). When we initially implemented this, we followed that documentation and so our project has version as `1+`.
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/4918760/201349461-2ed6afa4-f588-4a27-964b-62c9d4f57337.png">

Then I read specified version in github repo and decided to switch to that. 

<img width="862" alt="image" src="https://user-images.githubusercontent.com/4918760/201349811-6f755034-2060-446c-bd53-a53ad797ab52.png">

But after switching, it started crashing `can't downgrade database from version 2 to 1`.
<img width="479" alt="Screenshot 2022-11-11 at 6 52 44 PM" src="https://user-images.githubusercontent.com/4918760/201350123-ed0c6fb1-5fce-4b44-add2-e9e977872286.png">

I assumed because the resolved version with `1+` has database version 2 and version `1.6.1` has version 1.  I can not switch to 1.6.1 because that will crash all current installs and users will have to re-install which is not something we want to do.

Turns out, `1+` resolves to version `1.8.0-beta.1`.
<img width="578" alt="image" src="https://user-images.githubusercontent.com/4918760/201351368-7014d3c3-5d3f-4323-b5b7-e91e3e230a60.png">

So looks like I am stuck with `1.8.0-beta.1`. Please update the documentation.

**Comment by itsdebs** [comment]
@hbb20 Thank you for pointing out the issue with documentation. We had this beta release for internal use. It was not intended to be public at present. 
However we have this in pipeline and the downgrade issue will be fixed in the stable version release next week.

**Comment by desusai7** [comment]
Hey @hbb20 , 
Can you please use the SDK version `1.7.1` in which we have handled the dbDowngrade and let us know if you are facing any issues.

**Comment by hbb20** [comment]
That worked.. Thanks :)
