### ISSUE TITLE
Feature request: do not use device id

### ISSUE THREAD

**Issue by andreasgangso** [rudderlabs/rudder-sdk-android#230]
To comply with the google play families policies, which is a must for apps designed for children, you can't send deviceIds.

For our app we absolutely need this so I'm making a PR

**Comment by andreasgangso** [comment]
Fixed by #231

**Comment by andreasgangso** [comment]
https://github.com/rudderlabs/rudder-sdk-android/pull/242#issuecomment-1657782102

Any updates @desusai7?

**Comment by desusai7** [comment]
Hey @andreasgangso, 

We are working on it this sprint, we will notify you once we release it

**Comment by desusai7** [comment]
Hey @andreasgangso, 

This feature was released yesterday as part of version `1.18.0` and [here](https://www.rudderstack.com/docs/sources/event-streams/sdks/rudderstack-android-sdk/#withcollectdeviceid) are the docs for it.
