### ISSUE TITLE
`android-database-sqlcipher` has been deprecated in favour of `sqlcipher-android`

### ISSUE THREAD

**Issue by saran-epifi** [rudderlabs/rudder-sdk-android#413]
https://github.com/rudderlabs/rudder-sdk-android/blob/6bce2a91cac1cd2175b6822d912fbfb09220dc27/core/build.gradle#L57

[`android-database-sqlcipher` ](https://github.com/sqlcipher/android-database-sqlcipher) has been deprecated in favour of [`sqlcipher-android`](https://github.com/sqlcipher/sqlcipher-android)

Quote
> The android-database-sqlcipher project has been [officially deprecated](https://www.zetetic.net/blog/2023/08/31/sqlcipher-4.5.5-release#sqlcipher-android-455). The long-term replacement is [sqlcipher-android](https://github.com/sqlcipher/sqlcipher-android). Instructions for migrating from android-database-sqlcipher to sqlcipher-androidmay be found [here](https://www.zetetic.net/sqlcipher/sqlcipher-for-android-migration/).

Ref: https://github.com/sqlcipher/android-database-sqlcipher?tab=readme-ov-file#deprecated-library

Please migrate to the new active library from deprecated library

**Comment by itsdebs** [comment]
@saran-epifi Thanks for bringing this up. We will add this to our list of tasks.

**Comment by 1abhishekpandey** [comment]
Hey @saran-epifi,
We have updated the sqlcipher dependency. Please utilise the latest version [v1.23.0](https://github.com/rudderlabs/rudder-sdk-android/releases/tag/v1.23.0).
