### ISSUE TITLE
BUG : Profiler reports high CPU usage even in background

### ISSUE THREAD

**Issue by YvesDelerm** [rudderlabs/rudder-sdk-android#417]
Hello,
While investigating on our app's CPU and battery usage, we found out that Rudderstack has the thread that uses the most CPU in background for our app.

**To Reproduce**

1. Initialise Android SDK
2. Put our app in background
3. Look at Android Studio CPU profiler
4. Rudderstack's thread is the one that uses the most CPU (please see first screenshot)
5. Rudderstack's thread is waked up every 15s approximately 

**Expected behavior**
Rudderstack should use less CPU
Using `withSleepCount` parameter should allow Rudderstacks's thread to sleep for longer (for instance 50s as set in the example)
Using `withSessionTimeout` parameter is not applied to app in background (maybe when the app is killed ?)

**Screenshots**
<img width="744" alt="Capture d’écran 2024-04-12 à 14 44 12" src="https://github.com/rudderlabs/rudder-sdk-android/assets/45602569/d536875f-91ab-445a-81ec-55b89b0ea82c">
<img width="1216" alt="Capture d’écran 2024-04-12 à 14 47 35" src="https://github.com/rudderlabs/rudder-sdk-android/assets/45602569/66a6b4f3-3159-4237-83a8-555989d5bfd6">

**Version of the _Android_ SDK**
Rudder Android SDK : v. 1.22.0
No specific device model or OS version

**SDK initialisation snippet**
Please provide the following information:

1. Share the code snippet used for initializing the Android SDK
```
RudderClient.getInstance(
            context,
            rudderStackApiKey,
            RudderConfig.Builder()
                .withDataPlaneUrl(rudderStackUrl)
                .withLogLevel(logLevel)
                .withSleepCount(50)
                .withTrackLifecycleEvents(true)
                .withRecordScreenViews(true)
                .build(),
)
```

2. Indicate if the SDK initialization depends on any specific condition or event (e.g., initialization of the Android SDK after Firebase initialization or initialization in a callback) => no specific condition nor event

**Check for Correct Usage of _writeKey_ and _dataPlaneUrl_**
Confirm that the correct `writeKey` and `dataPlaneUrl` are utilized during SDK initialization => yes, they are 

Could you help us on that, please ? Thanks in advance

**Comment by itsdebs** [comment]
Thanks for reporting. We will check on this one.

**Comment by Oleur** [comment]
Any update on this one? :)

**Comment by YvesDelerm** [comment]
Hello, any news on this issue ?

**Comment by 1abhishekpandey** [comment]
Apologies for the delayed response. We are looking into this and will get back to you soon with an update.

**Comment by 1abhishekpandey** [comment]
Hey @YvesDelerm,
Did you get the chance to try out the above solution?

**Comment by YvesDelerm** [comment]
Hey @1abhishekpandey !
I will try it out next week and keep you informed.

**Comment by YvesDelerm** [comment]
Hey @1abhishekpandey, I just had a first look yesterday, I confirm that sleep interval parameter is taken into account, and from my first profiling, it seems that it can make some difference on battery consumption. I'm doing some more tests to make sure everything is ok, and I think we'll be able to close the this issue soon.

**Comment by YvesDelerm** [comment]
Hello @1abhishekpandey , it looks better now, we can close this issue.

**Comment by 1abhishekpandey** [comment]
Thanks for trying out the solution and providing confirmation. We will prioritize releasing this fix, likely by next week.

**Comment by 1abhishekpandey** [comment]
Hey @YvesDelerm, 
We have released a support update that will address your issues in [v1.24.0](https://github.com/rudderlabs/rudder-sdk-android/releases/tag/v1.24.0). Please update to this version and utilise the new API:
```
RudderClient.getInstance(
    this,
    WRITE_KEY,
    RudderConfig.Builder()
        .withDataPlaneUrl(DATA_PLANE_URL)
        .withLogLevel(RudderLogger.RudderLogLevel.VERBOSE)
        .withSleepCount(6)
        .withEventDispatchSleepInterval(2)         // NEW API
        .build()
)
```
