### ISSUE TITLE
Refactor anonymousId handling?

### ISSUE THREAD

**Issue by andreasgangso** [rudderlabs/rudder-sdk-android#473]
Hi.
I'm reading the code to better understand how anonymousId works.

I noticed this line:

https://github.com/rudderlabs/rudder-sdk-android/blob/369dede8004de6e3eb5b3bb15f53d5eb1758365d/core/src/main/java/com/rudderstack/android/sdk/core/RudderContext.java#L75

It looks like this is never propagated properly across the different classes. For example, RudderNetworkManager's `updateAnonymousIdHeaderString()` is not called as far as I can see.

I might be wrong, but either way I think it would be a good idea to refactor this in some way.
Maybe have the anonymousId only handled in a single place. And then other classes just listen to changes.

**Comment by 1abhishekpandey** [comment]
Hey @andreasgangso,

Thanks for bringing this to our attention.

To provide some context: [This](https://github.com/rudderlabs/rudder-sdk-android/blob/369dede8004de6e3eb5b3bb15f53d5eb1758365d/core/src/main/java/com/rudderstack/android/sdk/core/RudderContext.java#L75) line sets the anonymousId in events. The highlighted line is executed when the SDK is initialized for the first time. In RudderNetworkManager, the anonymousId is set [here](https://github.com/rudderlabs/rudder-sdk-android/blob/369dede8004de6e3eb5b3bb15f53d5eb1758365d/core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java#L112), and whenever a `RESET` call is made (i.e., rudderClient.reset(true)), we update it internally and call `updateAnonymousIdHeaderString()` at [this](https://github.com/rudderlabs/rudder-sdk-android/blob/369dede8004de6e3eb5b3bb15f53d5eb1758365d/core/src/main/java/com/rudderstack/android/sdk/core/EventRepository.java#L527) point.

We are already working on another version of the SDK where we will improve this. Please let me know if you have any other suggestions or issues.

**Comment by 1abhishekpandey** [comment]
We are closing this issue for now. Please feel free to reopen it or raise a new one if needed.
